### PR TITLE
Fix function in RaptorXFolder.sh

### PR DESCRIPTION
**Pull request by poliu2s**
Fix to bash function syntax to run.

### CODE REVIEW

**Comment by j3xugit** [comment]
thanks a lot, The way I use "function" indeed is not consistent with the grammar, but I do not have problems in running RaptorXFolder.sh. How about you ?

**Comment by poliu2s** [comment]
When I attempt to run I get the following error. I am on Ubuntu 18.04.

`./RaptorXFolder.sh: 35: ./RaptorXFolder.sh: Syntax error: "(" unexpected`

**Comment by j3xugit** [comment]
I have fixed the "function" issue in all .sh files. Please check them out. thanks again.

**Comment by poliu2s** [comment]
Yes, that works. Thank you!

**Pull request closed without merging**
